version: '3.5'

services:
  db:
    container_name: db-container
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dbvol:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  server:
    container_name: server-container
    image: node:19.1-alpine
    user: "${UID}:${GID}"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: [ "npm", "run", "start:dev" ]
    depends_on:
      - db

  pgadmin:
    container_name: admin-db-container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    volumes:
       - admvol:/var/lib/pgadmin
    ports:
      - '5050:80'
    depends_on:
      - db
  
volumes:
  dbvol:
  admvol: